### ISSUE TITLE
ORCID

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [Bai-Li-NOAA/Age_Structured_Stock_Assessment_Model_Comparison#5]
https://github.com/Bai-Li-NOAA/Age_Structured_Stock_Assessment_Model_Comparison/blob/f1eb024d3d33e7c33280d9f00abcf9120ea2ca90/DESCRIPTION#L9

@Bai-Li-NOAA I was trying to track down your ORCID for another project (i.e., {[saconvert](https://github.com/kellijohnson-NOAA/saconvert)}) but it is not available here. Can you please email me your ORCID or add it to this repo and I will copy it over to {savconvert}. Thank you.

**Comment by Bai-Li-NOAA** [comment]
Thanks Kelli. I just registered and got the ORCID identifier. Please find the id in the description file and let me know if you have any questions:
https://github.com/Bai-Li-NOAA/Age_Structured_Stock_Assessment_Model_Comparison/blob/a591ec6e1022893f75ab4bc4193f91fe49b51055/DESCRIPTION#L9

**Comment by kellijohnson-NOAA** [comment]
Yep, it worked. Thanks so much.
